# -*- coding: utf-8 -*-
"""Otra copia de Lab 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfwSEB9TBVv4HlOjZszEv7HutHjw6Kzy

# Laboratorio 1: Regresión en California

En este laboratorio deben hacer experimentos de regresión con el conjunto de datos "California Housing dataset".

Estudiarán el dataset, harán visualizaciones y seleccionarán atributos relevantes a mano.

Luego, entrenarán y evaluarán diferentes tipos de regresiones, buscando las configuraciones que mejores resultados den.
"""

import numpy as np
import matplotlib.pyplot as plt

"""## Carga del Conjunto de Datos

Cargamos el conjunto de datos y vemos su contenido.
"""

from sklearn.datasets import fetch_california_housing
X_california, y_california = fetch_california_housing(return_X_y=True, as_frame=True)
california = fetch_california_housing()

california.keys()

print(california['DESCR'])  # descripción del dataset
#california['feature_names'] # nombres de los atributos para cada columna de 'data'
#california['data']           # matriz con los datos de entrada (atributos)
#print(california['target']) # vector de valores a predecir

california['data'].shape, california['target'].shape

"""## División en Entrenamiento y Evaluación

Dividimos aleatoriamente los datos en 80% para entrenamiento y 20% para evaluación:
"""

from sklearn.model_selection import train_test_split
X, y = california['data'], california['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0)
X_train.shape, X_test.shape

y.shape

y_test.shape

"""## Ejercicio 1: Descripción de los Datos y la Tarea

Responda las siguientes preguntas:

1. ¿De qué se trata el conjunto de datos?
2. ¿Cuál es la variable objetivo que hay que predecir? ¿Qué significado tiene?
3. ¿Qué información (atributos) hay disponibles para hacer la predicción?
4. ¿Qué atributos imagina ud. que serán los más determinantes para la predicción?
5. ¿Qué problemas observa a priori en el conjunto de datos? ¿Observa posibles sesgos, riesgos, dilemas éticos, etc? Piense que los datos pueden ser utilizados para hacer predicciones futuras.

**No hace falta escribir código para responder estas preguntas.**

**Responder todas las preguntas acá.**

\

1. Es un conjunto de datos obtenido en base a grupos de bloques de un censo realizado en 1990 de California, Estados Unidos. Este se compone de $20640$ observaciones con $9$ variables diferentes.

\
***
\

2. La variable objetivo que hay que intentar predecir es: `MedHouseValue` (es el valor medio de las viviendas en los grupos de bloques)

\

***

\

3. Disponemos de los siguientes atributos:

    - `MedInc` :        Ingreso medio en el grupo de bloques
    - `HouseAge` :      Antiguedad media de la casa en el grupo de bloques
    - `AveRooms` :      Número promedio de habitaciones por vivienda
    - `AveBedrms` :     Número promedio de dormitorios por vivienda
    - `Population` :    Población total del grupo de bloques
    - `AveOccup` :      Número promedio de personas por vivienda
    - `Latitude` :      Latitud del grupo de bloque
    - `Longitude` :     Longitud del grupo de bloque

\

***

\

4. Considero que los más determinantes podrían ser: `AveRooms`, `MedInc`, `Latitude`, `Longitude`

Ya que:

- Lo primero nos da un indicio de qué tan grande es
- Lo segundo nos indica el ingreso del área (dando cierto "prestigio")
- Lo tercero nos dice en qué lugar está (más cerca del centro, más lejos, etc).

\

***

\

5. Algunas de las cosas que pienso que son importantes para hacer un análisis como este son:

- Presencia y calidad de servicios.
- Tamaño específico en metros cuadrados de la vivienda.
- Amueblamiento/equipamiento de la vivienda.

Sin embargo, estas no están presentes, pero en cambio si tenemos el ingreso medio por ejemplo, lo cual puede presentar un sesgo socioeconómico a la hora de trabajar con los datos.

## Ejercicio 2: Visualización de los Datos

1. Para cada atributo de entrada, haga una gráfica que muestre su relación con la variable objetivo.
2. Estudie las gráficas, identificando **a ojo** los atributos que a su criterio sean los más informativos para la predicción.
3. Para ud., ¿cuáles son esos atributos? Lístelos en orden de importancia.
"""

# 1. Resolver acá. Ayuda/ejemplo:
import seaborn as sns
sns.set_style('whitegrid')

# Ayuda/Ejemplo:
#feature = 'HouseAge'
#selector = california['feature_names'].index(feature)
#selector = (np.array(california['feature_names']) == 'HouseAge')
#plt.scatter(X[:, selector], y, facecolor="dodgerblue", edgecolor="k", label="datos")
#plt.title(feature)
#plt.show()

# # Hago un bucle y utilizo cada índice de cada feature en X[:, i]
# for i, feature in enumerate(california.feature_names):
#     plt.figure(figsize=(10, 8))
#     plt.scatter(X[:, i], y, c=y, cmap='cool', edgecolor="k", alpha=0.2)
#     plt.title(f"Relación entre {feature} y MedHouseValue")
#     plt.xlabel(feature)
#     plt.ylabel("MedHouseValue")
#     plt.grid(True)
#     plt.tight_layout()
#     plt.show()

# Hago un bucle y utilizo cada índice de cada feature en X[:, i]
for i, feature in enumerate(california.feature_names):
    plt.figure(figsize=(10, 8))
    plt.scatter(X[:, i], y, c=y, cmap='cool', edgecolor="k", alpha=0.4, s=8)
    plt.title(f"Relación entre {feature} y MedHouseValue")
    plt.xlabel(feature)
    plt.ylabel("MedHouseValue")

    # Set axis limits to focus on main distribution (95th percentile)
    x_95 = np.percentile(X[:, i], 95)
    y_95 = np.percentile(y, 95)
    plt.xlim(0, x_95 * 1.1)
    plt.ylim(0, y_95 * 1.1)

    plt.grid(True)
    plt.tight_layout()
    plt.show()

california['feature_names'][1] == feature

"""**3.** Los atributos que son más informativos para la predicción son:

`MedInc`, `Latitude`, `Longitude`

## Ejercicio 3: Regresión Lineal

1. Seleccione **un solo atributo** que considere puede ser el más apropiado.
2. Instancie una regresión lineal de **scikit-learn**, y entrénela usando sólo el atributo seleccionado.
3. Evalúe, calculando error cuadrático medio para los conjuntos de entrenamiento y evaluación.
4. Grafique el modelo resultante, junto con los puntos de entrenamiento y evaluación.
5. Interprete el resultado, haciendo algún comentario sobre las cualidades del modelo obtenido.

**Observación:** Con algunos atributos se puede obtener un error en test menor a 50.
"""

# 1. Resolver acá. Ayuda:
feature = 'MedInc'  # selecciono el atributo 'MedInc'
selector = california['feature_names'].index(feature)
selector = (np.array(california['feature_names']) ==  feature)
X_train_f = X_train[:, selector]
X_test_f = X_test[:, selector]
X_train_f.shape, X_test_f.shape

X_train_f[1]

# 2. Instanciar y entrenar acá.

# Una observación antes de empezar:
# los tipos de datos son todos numéricos y no hay valores nulos, por lo que es posible aplicar la regresión sin problemas

import pandas as pd

df = pd.DataFrame(california.data, columns=california.feature_names)

print(f"Dtypes:\n {df.dtypes}\n")
print(f"Valores null:\n {df.isnull().sum()}\n")

# ----------------------------------------------

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train_f, y_train)

# 3. Predecir y evaluar acá.

y_pred_train = model.predict(X_train_f)
y_pred_test = model.predict(X_test_f)

mse_train = mean_squared_error(y_train, y_pred_train)
mse_test = mean_squared_error(y_test, y_pred_test)

print(f"Training MSE: {mse_train:.4f}")
print(f"Eval MSE: {mse_test:.4f}")

# 4. Graficar acá. Ayuda:
x_start = min(np.min(X_train_f), np.min(X_test_f))
x_end = max(np.max(X_train_f), np.max(X_test_f))
x = np.linspace(x_start, x_end, 200).reshape(-1, 1)
plt.plot(x, model.predict(x), color="tomato", label="modelo")

plt.scatter(X_train_f, y_train, facecolor="dodgerblue", edgecolor="k", label="train")
plt.scatter(X_test_f, y_test, facecolor="white", edgecolor="k", label="test")
plt.title(feature)
plt.legend()
plt.show()

"""**5. Responder acá**

En base a la gráfica obtenida observamos que la dirección de la recta del modelo coincide con la tendencia general de los datos.

## Ejercicio 4: Regresión Polinomial

En este ejercicio deben entrenar regresiones polinomiales de diferente complejidad, siempre usando **scikit-learn**.

Deben usar **el mismo atributo** seleccionado para el ejercicio anterior.

1. Para varios grados de polinomio, haga lo siguiente:
    1. Instancie y entrene una regresión polinomial.
    2. Prediga y calcule error en entrenamiento y evaluación. Imprima los valores.
    3. Guarde los errores en una lista.
2. Grafique las curvas de error en términos del grado del polinomio.
3. Interprete la curva, identificando el punto en que comienza a haber sobreajuste, si lo hay.
4. Seleccione el modelo que mejor funcione, y grafique el modelo conjuntamente con los puntos.
5. Interprete el resultado, haciendo algún comentario sobre las cualidades del modelo obtenido.

**Observación:** Con algunos atributos se pueden obtener errores en test menores a 40 e incluso a 35.
"""

# 1. Resolver acá.

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

degrees = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
train_errors = []
test_errors = []

for degree in degrees:

    # Training
    pf = PolynomialFeatures(degree)
    lr = LinearRegression(fit_intercept=False)
    model = make_pipeline(pf, lr)
    model.fit(X_train_f, y_train)

    # Predict
    y_train_pred = model.predict(X_train_f)
    y_test_pred = model.predict(X_test_f)

    # Eval
    train_error = mean_squared_error(y_train, y_train_pred)
    test_error = mean_squared_error(y_test, y_test_pred)
    train_errors.append(train_error)
    test_errors.append(test_error)

    print(f"Polinomio grado {degree}: Training MSE = {train_error:.4f}, Eval MSE = {test_error:.4f}")

# 2. Graficar curvas de error acá.

# Graficar curva de errores

plt.plot(degrees, train_errors, color="blue", label="train")
plt.plot(degrees, test_errors, color="red", label="val")
plt.legend()
plt.xlabel("degree")
plt.ylabel("error")
plt.show()

# 4:
degree = degrees[np.argmin(test_errors)]
model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
model.fit(X_train_f, y_train)

print(f"Grado:{degree}")

plt.figure(figsize=(10, 6))
plt.scatter(X_train_f, y_train, color="dodgerblue", edgecolor="k", label="train")
plt.scatter(X_test_f, y_test, color="white", edgecolor="k", label="val")
plt.plot(x, model.predict(x), color="red", label="model")
plt.title(f"Regresión Polinomial")
plt.xlabel(feature)
plt.ylabel("MedHouseValue")
plt.legend()
plt.show()

"""## Ejercicio 5: Regresión con más de un Atributo

En este ejercicio deben entrenar regresiones que toman más de un atributo de entrada.

1. Seleccione **dos o tres atributos** entre los más relevantes encontrados en el ejercicio 2.
2. Repita el ejercicio anterior, pero usando los atributos seleccionados. No hace falta graficar el modelo final.
3. Interprete el resultado y compare con los ejercicios anteriores. ¿Se obtuvieron mejores modelos? ¿Porqué?
"""

# 1. Resolver acá. Ayuda (con dos atributos):
selector = (np.array(california['feature_names']) == 'HouseAge') | (np.array(california['feature_names']) == 'AveRooms')

X_train_fs = X_train[:, selector]
X_test_fs = X_test[:, selector]
X_train_fs.shape, X_test_fs.shape

# 2. Resolver acá.

"""**3. Responder acá.**

## Más ejercicios (opcionales)

### Ejercicio 6: A Todo Feature

Entrene y evalúe regresiones pero utilizando todos los atributos de entrada (va a andar mucho más lento). Estudie los resultados.

### Ejercicio 7: Regularización

Entrene y evalúe regresiones con regularización "ridge". Deberá probar distintos valores de "alpha" (fuerza de la regularización). ¿Mejoran los resultados?
"""